# permissions for end users to edit todoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubebuilder-external-resource-demo
    app.kubernetes.io/managed-by: kustomize
  name: todo-editor-role
rules:
- apiGroups:
  - external-resource.dev.external-resource.dev
  resources:
  - todoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - external-resource.dev.external-resource.dev
  resources:
  - todoes/status
  verbs:
  - get
