apiVersion: external-resource.dev.external-resource.dev/v1alpha1
kind: Todo
metadata:
  labels:
    app.kubernetes.io/name: kubebuilder-external-resource-demo
    app.kubernetes.io/managed-by: kustomize
  name: todo-sample
spec:
  # TODO(user): Add fields here
